services:

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - api_net

  api:
    build:
      context: ..
      dockerfile: server/Dockerfile
    container_name: earezki_api
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - QDRANT_HOST=qdrant
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://127.0.0.1:8000/health"]
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 3
    networks:
      - api_net

  cloudflared-blogapi:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-blogapi
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file:
      - .env
    network_mode: host

networks:
  api_net:
    driver: bridge
